# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l3tWpXU-ktn3UlGMwYT16xeb4JSGGcPr
"""

# Calculator functions
import math


def add(x, y):
    return x + y


def subtract(x, y):
    return x - y


def divide(x, y):
    if y == 0:
        return "Cannot divide by zero"
    return x / y


def multiply(x, y):
    return x * y


def square(x):
    return x * x


def power(x, y):
    return x ** y


def sqrt(x):
    return math.sqrt(x)

#test statements
def test_add():
    results = add(1, 2)
    assert results == 3

def test_divide():
    results = divide(6, 2)
    assert results == 3


def test_divide_by_zero():
    results = divide(99, 0)
    assert type(results) == str

def test_multiply():
    results = multiply(2, 3)
    assert results == 6

def test_power():
    results = power(3, 2)
    assert results == 9

    results = power(3, 3)
    assert results == 27

def test_square():
    results = square(3)
    assert results == 9

def test_subtract():
    results = subtract(10, 7)
    assert results == 3

def test_sqrt():
    results = sqrt(9)
    assert results == 3

    results = sqrt(16)
    assert results == 4

while True:
    print("Select operation:")
    print("1. Add")
    print("2. Subtract")
    print("3. Divide")
    print("4. Multiply")
    print("5. Square")
    print("6. Power")
    print("7. Square Root")
    print("8. Exit")

    choice = input("Enter choice (1/2/3/4/5/6/7/8): ")

    if choice in ['1', '2', '3', '4', '6', '7']:
        num1 = float(input("Enter first number: "))
        num2 = float(input("Enter second number: "))

        if choice == '1':
            print("Result: ", add(num1, num2))
        elif choice == '2':
            print("Result: ", subtract(num1, num2))
        elif choice == '3':
            print("Result: ", divide(num1, num2))
        elif choice == '4':
            print("Result: ", multiply(num1, num2))
        elif choice == '6':
            print("Result: ", power(num1, num2))
        elif choice == '7':
            print("Result: ", sqrt(num1))

    elif choice == '5':
        num = float(input("Enter a number: "))
        print("Result: ", square(num))

    elif choice == '8':
        print("Exiting calculator. Goodbye!")
        break

    else:
        print("Invalid input. Please enter a valid option.")